# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-07 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0002_recipe_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='Contree',
        ),
        migrations.RenameModel(
            old_name='Quantity',
            new_name='Quantite',
        ),
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Recette',
        ),
        migrations.RenameField(
            model_name='recette',
            old_name='category',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='recette',
            old_name='country',
            new_name='contree',
        ),
    ]
