# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-07 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0004_auto_20171107_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantite',
            options={'ordering': ['dequoi', 'ingredient']},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sorte',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='quantite',
            name='dequoi',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
