# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-10 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0005_auto_20171107_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='quantite',
        ),
        migrations.AddField(
            model_name='quantite',
            name='recette',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recette.Recette'),
            preserve_default=False,
        ),
    ]
