# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-18 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0006_auto_20171110_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Illustration'),
        ),
    ]
